apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sherlock
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: sherlock-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: sherlockdb
        - name: MYSQL_ROOT_PASSWORD
          value: thiswillbechangeonsetupscript
        image: mariadb:latest
        imagePullPolicy: ""
        name: sherlock-mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-claim0
        persistentVolumeClaim:
          claimName: mysql-claim0
status: {}
