apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sherlock
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: sherlock-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: SHERLOCK_ENV
          value: PROD
        image: leogalani/sherlockqa:latest
        imagePullPolicy: ""
        name: sherlock
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
