apiVersion: v1
kind: Service
metadata:
  namespace: sherlock
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: sherlock-web
spec:
  ports:
  - name: "sherlock-web"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
